module.exports = {
  BASE: "/",
  BY_ID: "/:id",
  AUTH: "/auth",
  CATEGORY: "/categories",
  PRODUCT: "/products",
  USER: "/users",
  ORDER: "/orders",
  REFRESH: "/refresh",
  ANALYTICS: "/analytics",
  SLIDER: "/sliders",
  VIDEO: "/videos",
  REFRESH: "/refresh",
  ADMIN_LIST: "/admin/list",
  GET_ONE: "/one",
  USER_ONLY: "/user",
  EXPIRED: "expired",
  REGISTER: "/register",
  BANNER: "/banners",
  SELLING: "/selling",
  NOTIFICATION: "/notifications",
  POST: "/posts",
  CHATBOT: "/chatbot",
  PRODUCT_SIZE: "/product-sizes",
  CART: "/cart",
  RATING: "/ratings",
};
